#ifndef ETHERNETSCANNERSDKDEFINE_H
#define ETHERNETSCANNERSDKDEFINE_H

#define ETHERNETSCANNER_INVALIDHANDLE                       -1000

#define ETHERNETSCANNER_TCPSCANNERDISCONNECTED              0
#define ETHERNETSCANNER_TCPSCANNERCONNECTED                 3

#define ETHERNETSCANNER_PEAKSPERCMOSSCANLINEMAX	            4
#define ETHERNETSCANNER_SCANXMAX                            2048
#define ETHERNETSCANNER_BUFFERSIZEMAX                       2050 * 2050

#define ETHERNETSCANNER_GETINFOSIZEMAX                      128 * 1024
#define ETHERNETSCANNER_GETINFOINVALIDXML                   -4
#define ETHERNETSCANNER_GETINFONOVALIDINFO                  -3
#define ETHERNETSCANNER_GETINFOSMALLBUFFER                  -2
#define ETHERNETSCANNER_ERROR                               -1

#define ETHERNETSCANNER_GETXZINONEWSCAN                     -1
#define ETHERNETSCANNER_GETXZIINVALIDLINDATA                -2
#define ETHERNETSCANNER_GETXZIINVALIDBUFFER                 -3

#define ETHERNETSCANNER_GETRANGEIMAGENONEWSCAN				-1
#define ETHERNETSCANNER_GETRANGEIMAGINVALIDLINDATA			-2
#define ETHERNETSCANNER_GETRANGEIMAGENOBUFFER				-3
#define ETHERNETSCANNER_GETRANGEIMAGESMALLBUFFER			-4

#define ETHERNETSCANNER_READDATAOK                           0
#define ETHERNETSCANNER_READDATASMALLBUFFER                 -1
#define	ETHERNETSCANNER_READDATANOTSUPPORTEDMODE            -2
#define ETHERNETSCANNER_READDATAFEATURENOTDEFINED           -3
#define ETHERNETSCANNER_READDATANOSCAN                      -4
#define ETHERNETSCANNER_READDATAFAILED                      -5

#define ETHERNETSCANNER_WRITEDATAINVALIDSOCKET              -1
#define ETHERNETSCANNER_WRITEDATAINVALIDARGUMENT            -2
#define ETHERNETSCANNER_WRITEDATAARGUMENTOUTOFRANGE         -3

#define ETHERNETSCANNER_OK                                  0

#endif //ETHERNETSCANNERSDKDEFINE_H